name = "Struct2JSONSchema"
uuid = "6b9a66ba-ce23-4e49-9189-ad500babf267"
version = "0.3.0"
authors = ["abap34 <abap0002@gmail.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
Dates = "1.11.0"
Logging = "1.11.0"
OrderedCollections = "1.8.1"
REPL = "1.11.0"
SHA = "0.7.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
